version: "3.9"

# services: 
#   postgres:
#     image: postgis/postgis
#     container_name:
services:
  api:
    image: cruztan/api:prueba
    container_name: prueba_api
    ports:
      - "8000:8000"
    networks: 
      - apieventos
    restart: always
    depends_on: 
     - db
  db:
    image: postgres:9.6.24-alpine
    ports:
      - "5434:5432"
    container_name: bd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: eventos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    restart: always
      
    networks: 
      - apieventos


networks:
  apieventos:
    name: "apieventos"